FROM python:3.13-slim

WORKDIR /usr/src/app

RUN pip install --no-cache-dir uv

COPY frontend/pyproject.toml ./pyproject.toml
RUN uv sync --no-dev

COPY frontend/src ./src

EXPOSE 8000

CMD ["uv", "run", "flet", "run", "--web", "--host", "0.0.0.0", "--port", "8000", "src/main.py"]
